
name: Java CI with Gradle and CodeDeploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Archive the artifact
        uses: actions/upload-artifact@v3
        with:
          name: introduce
          path: build/libs/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: introduce

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2 with CodeDeploy
        uses: aws-actions/aws-codedeploy-deploy@v2
        with:
          application-name: ${{ secrets.CODEDEPLOY_APPLICATION_NAME }}
          deployment-group-name: ${{ secrets.CODEDEPLOY_DEPLOYMENT_GROUP_NAME }}
          deployment-config-name: CodeDeployDefault.OneAtATime
          revision-type: S3
          s3-location:
            bucket: ${{ secrets.S3_BUCKET_NAME }}
            key: application/${{ github.sha }}/introduce.zip
            bundle-type: zip
      - name: Zip artifact
        run: zip -r introduce.zip introduce/*

      - name: Upload to S3
        run: aws s3 cp introduce.zip s3://${{ secrets.S3_BUCKET_NAME }}/application/${{ github.sha }}/introduce.zip
